apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-k3s-app
  namespace: argocd
spec:
  project: default
  source:
    # 🌟 Helm 변수 주입을 통해 IP를 동적으로 가져옵니다.
    repoURL: '{{ .Values.global.gitlabUrl }}/root/gitops-repo.git'
    path: kubernetes/apps/app
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
