apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    # 프로메테우스 커뮤니티 공식 헬름 레포지토리 주소
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 56.6.2  # 최신 안정화 버전 계열
    helm:
      # 필요한 컴포넌트들을 true로 켜서 헬름이 한방에 빌드하게 만듬
      values: |
        prometheus:
          enabled: true
        grafana:
          enabled: true
        alertmanager:
          enabled: true
        kube-state-metrics:
          enabled: true
        prometheus-node-exporter:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #  추가된 부분 1: CRD 용량 초과 에러 방지를 위한 서버 사이드 어플라이
    syncOptions:
    - ServerSideApply=true
    # 추가된 부분 2: 덩치가 큰 모니터링 스택의 안정적인 배포를 위한 자동 재시도
    retry:
      limit: 5 # 최대 5회까지 재시도
      backoff:
        duration: 5s # 1차 실패 시 5초 대기
        factor: 2    # 실패할 때마다 대기 시간을 2배씩 늘림 (5초 -> 10초 -> 20초)
        maxDuration: 3m # 아무리 길어져도 최대 3분 간격으로 계속 찌름
