apiVersion: v1
kind: Service
metadata:
  name: hello-k3s-service    # 서비스 이름
  namespace: dev-apps
spec:
  type: NodePort             # 로컬 테스트를 위해 외부 접속이 가능한 NodePort 타입 사용
  selector:
    app: hello-k3s           # Deployment에서 설정한 라벨과 똑같아야 연결됨 (매우 중요!)
  ports:
  - protocol: TCP
    port: 80                 # 서비스 자체가 사용하는 포트
    targetPort: 80           # 파드(컨테이너) 내부의 포트
    nodePort: 30080          # 윈도우 크롬 등 외부에서 실제로 접속할 포트 (30000~32767 사이)
